# Generated by Django 4.2.16 on 2026-05-02 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('slug', models.SlugField(max_length=72, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('title', models.CharField(max_length=256)),
                ('slug', models.SlugField(max_length=280, unique=True)),
                ('director', models.CharField(max_length=128)),
                ('cast', models.JSONField(default=list)),
                ('summary', models.TextField()),
                ('backdrop_path', models.CharField(blank=True, max_length=512)),
                ('poster_path', models.CharField(blank=True, max_length=512)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('popularity_score', models.FloatField(default=0.5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('genres', models.ManyToManyField(blank=True, related_name='movies', to='catalog.genre')),
            ],
            options={
                'ordering': ['-popularity_score', 'title'],
            },
        ),
    ]
